name: Build Workflow
on:
  push:
    branches:
      - feature/juwon

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.23'

      - name: Run tests
        run: go test ./...

  build-and-upload:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: '1.23'

      - name: Build the application
        run: go build -o realestate

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: realestate
          path: realestate

  download-artifact:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v7
        with:
          name: realestate
          path: realestate